//! OpenSees export operations.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result};

use crate::model::{MaterialDef, Project, SectionDef};

/// Exports the current project to a simple OpenSees TCL script.
pub fn export_opensees_tcl(project: &Project, path: impl AsRef<Path>) -> Result<()> {
    let out_path = path.as_ref();
    let mut lines: Vec<String> = Vec::new();

    lines.push("# Auto-generated by dask-modeler".to_string());
    lines.push("wipe".to_string());
    lines.push("model BasicBuilder -ndm 3 -ndf 6".to_string());
    lines.push(String::new());

    let mut node_ids: Vec<u32> = project.nodes.keys().copied().collect();
    node_ids.sort_unstable();
    for node_id in node_ids {
        if let Some(node) = project.nodes.get(&node_id) {
            lines.push(format!("node {} {} {} {}", node.id, node.x, node.y, node.z));
            if node.restraints.iter().any(|r| *r) {
                lines.push(format!(
                    "fix {} {} {} {} {} {} {}",
                    node.id,
                    bool_to_fix(node.restraints[0]),
                    bool_to_fix(node.restraints[1]),
                    bool_to_fix(node.restraints[2]),
                    bool_to_fix(node.restraints[3]),
                    bool_to_fix(node.restraints[4]),
                    bool_to_fix(node.restraints[5]),
                ));
            }
        }
    }

    lines.push(String::new());
    lines.push("# Material definitions".to_string());
    let mut material_map: BTreeMap<u32, MaterialDef> = BTreeMap::new();
    for material in project.materials.values() {
        material_map.insert(material.id, material.clone());
    }
    if material_map.is_empty() {
        let balsa = MaterialDef::balsa_default(1);
        material_map.insert(1, balsa);
        lines.push("# No user material found; using default Balsa".to_string());
    }
    for material in material_map.values() {
        lines.push(format!(
            "nDMaterial ElasticIsotropic {} {} {} {}",
            material.id, material.e, material.nu, material.density
        ));
    }

    lines.push(String::new());
    lines.push("# Geometric transformation".to_string());
    lines.push("geomTransf Linear 1".to_string());

    let mut section_map: BTreeMap<u32, SectionDef> = BTreeMap::new();
    for section in project.sections.values() {
        section_map.insert(section.id, section.clone());
    }
    if section_map.is_empty() {
        lines.push(
            "# No user section found; using default 6x6 rectangular approximation".to_string(),
        );
    }

    lines.push(String::new());
    lines.push("# Element definitions".to_string());
    let mut element_ids: Vec<u32> = project.elements.keys().copied().collect();
    element_ids.sort_unstable();
    for element_id in element_ids {
        let Some(element) = project.elements.get(&element_id) else {
            continue;
        };

        let (area, iy, iz, j) = element
            .section_id
            .and_then(|id| section_map.get(&id))
            .map(section_properties_for_opensees)
            .unwrap_or((36.0, 108.0, 108.0, 216.0));

        let (e, g) = element
            .material_id
            .and_then(|id| material_map.get(&id))
            .map(|m| (m.e, m.g))
            .unwrap_or((3500.0, 1346.0));

        lines.push(format!(
            "element elasticBeamColumn {} {} {} {} {} {} {} {} {} 1",
            element.id, element.node_i, element.node_j, area, e, g, j, iy, iz
        ));
    }

    if let Some(parent) = out_path.parent()
        && !parent.as_os_str().is_empty()
    {
        fs::create_dir_all(parent).with_context(|| {
            format!(
                "failed to create export directory for opensees file: {}",
                parent.display()
            )
        })?;
    }
    fs::write(out_path, lines.join("\n"))
        .with_context(|| format!("failed to write opensees export: {}", out_path.display()))?;
    Ok(())
}

fn section_properties_for_opensees(section: &SectionDef) -> (f64, f64, f64, f64) {
    // OpenSees elasticBeamColumn expects A E G J Iy Iz.
    // Current model stores Ix/Iy; use Iy as Iy and Ix as Iz as a consistent mapping.
    (section.area, section.iy, section.ix, section.j)
}

fn bool_to_fix(value: bool) -> u8 {
    if value { 1 } else { 0 }
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::time::{SystemTime, UNIX_EPOCH};

    use crate::io::opensees_export::export_opensees_tcl;
    use crate::model::{ElementData, ElementType, NodeData, Project};

    #[test]
    fn opensees_export_creates_script_file() {
        let mut project = Project::new("opensees-test");
        project.insert_node(NodeData::new(1, 0.0, 0.0, 0.0, 0, "podium"));
        project.insert_node(NodeData::new(2, 1.0, 0.0, 0.0, 0, "podium"));
        project.insert_element(ElementData::new(1, 1, 2, ElementType::BeamX, 1.0));

        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock before unix epoch")
            .as_millis();
        let path = std::env::temp_dir().join(format!("dask_modeler_opensees_{stamp}.tcl"));
        export_opensees_tcl(&project, &path).expect("opensees export should succeed");

        let text = fs::read_to_string(&path).expect("exported tcl should be readable");
        fs::remove_file(&path).expect("temp tcl file should be removable");
        assert!(text.contains("model BasicBuilder -ndm 3 -ndf 6"));
        assert!(text.contains("element elasticBeamColumn 1 1 2"));
    }
}
